spring:
  datasource:
    username: dawid
    password: passat
    url: jdbc:mysql://localhost:3306/TGbook

  jpa:
    show-sql: true
    hibernate:
      ddl_auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  output:
    ansi:
      enabled: ALWAYS